#!/usr/bin/env bash
#
# Install the Kubedok agent on a Docker host.
#
#   agent-install.sh --token <registration-token> --api-url https://kubedok.example.com
#   agent-install.sh --token <token>                 # on the control-plane host
#
# Runs on any Docker host, with or without a Kubedok control plane installed.
# The agent is deliberately a separate install (/opt/kubedok-agent) with its
# own lifecycle: updating the control plane must never restart every agent.
#
# Generate the registration token in the Kubedok UI first.
set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [ -f "${SCRIPT_DIR}/common.sh" ]; then
  # shellcheck source=common.sh
  . "${SCRIPT_DIR}/common.sh"
else
  echo "Cannot find common.sh next to agent-install.sh" >&2
  exit 1
fi

AGENT_ROOT="${KUBEDOK_AGENT_ROOT:-/opt/kubedok-agent}"
TOKEN=""
API_URL=""
HOST_ADDRESS=""
RELEASE_REF=""

while [ $# -gt 0 ]; do
  case "$1" in
    --token) TOKEN="$2"; shift 2 ;;
    --api-url) API_URL="$2"; shift 2 ;;
    --host-address) HOST_ADDRESS="$2"; shift 2 ;;
    --release) RELEASE_REF="$2"; shift 2 ;;
    -h|--help) sed -n '2,12p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) die "Unknown option: $1" ;;
  esac
done

require_root
require_cmd docker curl jq

# Inherit control-plane settings when one is installed here.
if [ -f "${KUBEDOK_CONFIG_FILE}" ]; then
  load_config
  [ -z "${API_URL}" ] && API_URL="http://127.0.0.1:${KUBEDOK_HTTP_PORT:-80}"
  [ -z "${RELEASE_REF}" ] && RELEASE_REF="${KUBEDOK_RELEASE:-stable}"
fi
RELEASE_REF="${RELEASE_REF:-stable}"

[ -n "${TOKEN}" ] || die "A registration token is required: --token <token>. Generate one in the Kubedok UI."
[ -n "${API_URL}" ] || die "The API URL is required on a host without a control plane: --api-url https://kubedok.example.com"

# Resolve the agent image digest from the release manifest, so an agent is
# pinned exactly like every other component.
log "Resolving the agent image for release '${RELEASE_REF}'"
MANIFEST="$(mktemp)"
LOCAL_MANIFEST="${KUBEDOK_CURRENT_LINK}/release.json"
if [ -f "${LOCAL_MANIFEST}" ] && { [ "${RELEASE_REF}" = "stable" ] || [ "${RELEASE_REF}" = "$(current_release 2>/dev/null)" ]; }; then
  cp "${LOCAL_MANIFEST}" "${MANIFEST}"
  validate_manifest "${MANIFEST}"
else
  resolve_manifest "${RELEASE_REF}" "${MANIFEST}" >/dev/null
fi

AGENT_IMAGE="$(manifest_image agent "${MANIFEST}")"
AGENT_RELEASE="$(manifest_field release "${MANIFEST}")"
ok "Agent image: ${AGENT_IMAGE}"

log "Checking the control plane at ${API_URL}"
if ! curl -fsS --max-time 15 -o /dev/null "${API_URL}/api/health"; then
  die "Cannot reach ${API_URL}/api/health from this host. The agent needs outbound access to the control plane."
fi
ok "Control plane reachable"

mkdir -p "${AGENT_ROOT}"
chmod 700 "${AGENT_ROOT}"

# Ship a compose file so the agent has the same lifecycle tooling everywhere,
# whether or not this host runs a control plane.
if [ -f "${KUBEDOK_CURRENT_LINK}/compose/agent.yml" ]; then
  install -m 644 "${KUBEDOK_CURRENT_LINK}/compose/agent.yml" "${AGENT_ROOT}/docker-compose.yml"
else
  fetch_url "${KUBEDOK_RELEASE_BASE_URL}/compose/agent.yml" "${AGENT_ROOT}/docker-compose.yml"
fi

{
  printf '# Generated by agent-install.sh. Edit KUBEDOK_API_URL here and re-run restart.\n'
  printf 'KUBEDOK_IMAGE_AGENT=%s\n' "${AGENT_IMAGE}"
  printf 'KUBEDOK_API_URL=%s\n' "${API_URL}"
  printf 'KUBEDOK_REGISTRATION_TOKEN=%s\n' "${TOKEN}"
  printf 'KUBEDOK_HOST_ADDRESS=%s\n' "${HOST_ADDRESS}"
  printf 'KUBEDOK_SYNC_INTERVAL_SECS=%s\n' "${KUBEDOK_SYNC_INTERVAL_SECS:-15}"
  printf 'KUBEDOK_AGENT_LOG=%s\n' "${KUBEDOK_AGENT_LOG:-kubedok_agent=info}"
  printf 'KUBEDOK_AGENT_RELEASE=%s\n' "${AGENT_RELEASE}"
} > "${AGENT_ROOT}/agent.env"
chmod 600 "${AGENT_ROOT}/agent.env"
rm -f "${MANIFEST}"

log "Pulling the agent image"
docker pull -q "${AGENT_IMAGE}" >/dev/null || die "Could not pull ${AGENT_IMAGE}"

log "Starting the agent"
# shellcheck disable=SC2046
$(compose_cmd) --env-file "${AGENT_ROOT}/agent.env" -f "${AGENT_ROOT}/docker-compose.yml" up -d

sleep 5
state="$(docker inspect -f '{{.State.Status}}' kubedok-agent 2>/dev/null || echo missing)"
if [ "${state}" != "running" ]; then
  err "The agent is not running (state: ${state})."
  docker logs --tail 30 kubedok-agent 2>&1 | sed 's/^/      /' >&2 || true
  die "Agent installation failed."
fi

ok "Agent ${AGENT_RELEASE} is running"
printf '\n'
printf '  Config   %s/agent.env\n' "${AGENT_ROOT}"
printf '  Logs     docker logs -f kubedok-agent\n'
printf '  Update   %s/agent-update.sh\n' "${SCRIPT_DIR}"
printf '\n'
printf '  The host should appear in the Kubedok UI within a few seconds.\n\n'
